import { chromium } from 'playwright-core';
const mobile = process.argv[2]==='m';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: mobile?{width:390,height:800}:{width:1280,height:800}, hasTouch: mobile, isMobile: mobile });
const p = await ctx.newPage(); const errs=[];
p.on('pageerror',e=>errs.push(e.message)); p.on('console',m=>m.type()==='error'&&!/CERT|404|ERR_/.test(m.text())&&errs.push(m.text()));
await p.goto('http://localhost:8095/?cap=b_pwd',{waitUntil:'domcontentloaded'});
await p.waitForSelector('.bp-field input',{timeout:20000});
const t0=Date.now(); const el=()=>((Date.now()-t0)/1000).toFixed(0)+'s';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const inp=p.locator('.bp-field input').first();
const state=()=>p.evaluate(()=>({n:document.querySelectorAll('.bp-r').length, ok:document.querySelectorAll('.bp-r.ok').length, v:document.querySelector('.bp-field input').value, timer:document.querySelector('.hud-time,#time,[class*=time]')?.textContent, btn:!document.querySelector('.bk-btn').disabled}));
const tx=async s=>{ for(const ch of s){ await p.keyboard.type(ch,{delay:0}); await sleep(130);} };
await inp.click(); await sleep(2500);
const rt=()=>p.evaluate(()=>[...document.querySelectorAll('.bp-r')].map(r=>r.innerText.replace(/\n/g,' ')).reverse());
let rules=await rt(); const word=(rules.find(r=>/Doit contenir le mot/.test(r)||0)||'');
// stage 1
await tx('Aa1!13'); await sleep(1500); console.log(el(), JSON.stringify(await state()));
await tx('janvier'); await sleep(1500);
rules=await rt(); console.log(el(), rules.length, rules.at(-1));
const w=(await p.evaluate(()=>{const r=[...document.querySelectorAll('.bp-r')].map(r=>r.innerText);const m=r.find(x=>/Doit contenir le mot/.test(x));return m?m.match(/« (.*?) »/)[1]:null;}));
console.log('word',w);
await p.screenshot({path:`/tmp/claude-0/s/pwd_play1_${mobile?'m':'d'}.png`});
await tx(w||'');await sleep(1200); 
await p.locator('.bp-chip').nth(5).click(); await sleep(1500);
const code=await p.evaluate(()=>[...document.querySelectorAll('.bp-code u')].map(u=>u.textContent).join(''));
console.log('code',code, el());
await tx(code); await sleep(1500);
// remove e: retype whole thing
console.log(el(), 'rules',(await rt()).length);
await p.screenshot({path:`/tmp/claude-0/s/pwd_play2_${mobile?'m':'d'}.png`});
